### ISSUE TITLE
Items under maintenance should persist disabled if Kytos restart

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/maintenance#28]
If kytos gets restarted the items under maintenance should remain disable and should be enabled after the maintenance window finishes. The way we are handling some items for now can lead to some of them gets theirs normal state if kytos gets restarted during a MW.

**Comment by italovalcy** [comment]
One example is show in https://github.com/kytos-ng/topology/pull/13

**Comment by viniarck** [comment]
@Ktmi, this one has been completely covered, hasn't it? If positive, you can close this issue too
