### ISSUE TITLE
Implement `register_status_func` hooks

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/maintenance#58]
`maintenance`, following the `register_status_func` hooks pattern should update it accordingly when it enters in maintenance, in addition to keep sending the existing events, that way the `status` attribute is correctly detected as `EntityStatus.DOWN` playing well with other features and solving this issue here https://github.com/kytos-ng/topology/issues/62, so on topology all of the disabled/deactivations are supposed to be removed too, only notifications on topology should remain.

**Comment by Ktmi** [comment]
Closed with #78
