### ISSUE TITLE
Old events in the README are discontinued and new events are not mentioned

### ISSUE THREAD

**Issue by Auwate** [kytos-ng/maintenance#98]
# Context

The README file mentions the event `kytos/maintenance.(start|end)_(switch|uni|link}`. However, this event was discontinued on 2023-06-26 in the CHANGELOG in favor of `topology.interruption.[start|end]`. Please update the README to reflect new changes to events.

# Additional Information

This is where the CHANGELOG mentions the event:

```
[2023.1.0] - 2023-06-26
***********************

Added
...

Fixed
...

Changed
=======
- Maintenance start and end no longer produce ``kytos/maintenance.*`` events, and instead produce ``topology.interruption.[start|end]`` events to work with blueprint EP0037
- Creating a maintenance window now checks if all devs exist and rejects the window, except when the attribute ``ignore_no_exists`` is set to True
```

**Comment by viniarck** [comment]
Good finding @Auwate. Yes, it needs to be removed from the README.

**Comment by Auwate** [comment]
Thanks @viniarck. Would you like me to create an MR on this one?

**Comment by viniarck** [comment]
> Thanks @viniarck. Would you like me to create an MR on this one?

@Auwate much appreciated if you can send a PR updating it. Otherwise, I can do it in the next days too.

**Comment by Auwate** [comment]
@viniarck  Here is the MR: https://github.com/kytos-ng/maintenance/issues/98
